table Queries
	lineageTag: 06d9e1ab-b60a-4b1d-8ea6-ec65090c7ea9

	column Table
		dataType: string
		lineageTag: 19a6f12b-9504-4d06-8c75-9d945d3682d2
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Query
		dataType: string
		lineageTag: a626b6a3-3c88-4b0a-8a7c-35d99349256c
		summarizeBy: none
		sourceColumn: Query

		annotation SummarizationSetBy = Automatic

	partition Queries = m
		mode: import
		queryGroup: PAR
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WcnN0DlEoSUzKSVXSUQp29XEFcmPyFBS0YvLcgvx9FdISk0viUxJLUmPywj1cg1wVDG0NQfKOfi4KIOH45PwchZhSAwPjVFswbWSuHB1flJiXnhpcklhU4gJUEwsRx6InGU2La14KkgaQPbq6eGwyMjAy1TU00DU0JWgDXKkZhK8UqxOt5OLpi8/vKZm58WBpkvxeTJK3U+no41gA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Table = _t, Query = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Table", type text}, {"Query", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

